implemented Data Table component
PrepareDev/data-table pull request #1
Opened 2023-09-28 18:49 UTC by snusEbjoer

something got done something not...

2023-09-28 19:43 UTC, tyrkinn requested changes

2023-09-28 19:43 UTC, tyrkinn commented on src/components/DataTable.tsx
> +                    </tr>
Тайтлы столбцов не должны быть захаркожены. Принимай в пропсах

2023-09-28 19:43 UTC, tyrkinn commented on src/components/DataTable.tsx
> +export type DataTableProps = {
Нужно принимать пропсы для стилизации. Тут у тебя два пути: либо добавить пропсы c tailwind классами для каждого элемента таблицы, либо написать типизированную тему и через неё уже менять визуал и положение. Напоминаю, что ограничения в библиотеках нет. Если решишь писать тему, то можешь посмотреть на [Panda CSS](https://panda-css.com/)

2023-09-28 19:43 UTC, tyrkinn commented on src/components/DataTable.tsx
> +                            <td>{t.description}</td>
Поля соответственно тоже не должны быть захардкожены. Придумай контракт для отображения данных, который не зависит от конкретной апишки

2023-09-28 19:43 UTC, tyrkinn commented on src/components/DataTable.tsx
> +            <h1 className="font-bold text-5xl"> Data Table Project </h1>
Тайтла не должно быть в таблице, такого требования не было

2023-09-28 19:56 UTC, tyrkinn reviewed
В дальнейшем пиши нормальные сообщения в PR-ах. Как пример:

```markdown
This fixes all cases where `binaryToString` stopped fooing, by making explicit
the need of the necessary encoding. 

It:
- Fixes `binaryToString`, and adds a new encoding parameter
- Updates usage of `binaryToString` across the code to pass the correct encoding
  parameter

`binaryToString` used to infer the encoding, which used an unsupported
feature[1] that was unsafe and caused problems in some situations[2]. In order
to avoid the issue, we will stop inferring the encoding and instead require it
to be passed down.

1: https://example.org/encoding-detection
2: https://example.org/issues-with-encoding
Jira: ABC-123
```

2023-09-30 12:02 UTC, tyrkinn commented on src/components/DataTable.tsx
> +export type DataTableProps = {
@snusEbjoer Что по поводу этой правки? Вынесем в отдельную задачу?

2023-09-30 12:03 UTC, snusEbjoer commented on src/components/DataTable.tsx
> +export type DataTableProps = {
Да

2023-09-30 12:05 UTC, tyrkinn commented on src/components/DataTable.tsx
> +            <h1 className="font-bold text-5xl"> Data Table Project </h1>
@snusEbjoer Не пофикшено

2023-09-30 12:16 UTC, tyrkinn commented on src/components/DataTable.tsx
> +    const rows = Object.values(table)
Переменная `rows` тебе здесь абсолютно ненужна. Ты можешь использовать table.map вместо rows.map ниже

2023-09-30 12:17 UTC, tyrkinn commented on src/components/DataTable.tsx
> +
Для случая когда в table приходит пустой массив, предлагаю принимать headers отдельно как массив строк.

2023-09-30 12:18 UTC, tyrkinn commented on src/components/DataTable.tsx
> +    console.log(rows)
Когда ты кидаешь PR не должно оставаться console.log ов

2023-09-30 12:19 UTC, tyrkinn commented on src/components/DataTable.tsx
> +                    {rows.map(row => <tr>{Object.values(row).map(v => <td>{v}</td>)}</tr>)}
Добавить ключи ко всему в map. Учитывая что у тебя никогда не изменяется порядок и ты ничего не удаляешь, это могут быть просто индексы по массиву

2023-09-30 12:22 UTC, tyrkinn requested changes

2023-09-30 12:22 UTC, tyrkinn commented on src/components/DataTable.tsx
> +                        {tableHeaders.map(k => <th>{k}</th>)}
Здесь тоже добавить key

2023-09-30 12:22 UTC, tyrkinn commented on src/components/DataTable.tsx
> +            <h2 className="text-4xl"> Implement me </h2>
Это можно убрать

2023-09-30 12:22 UTC, tyrkinn commented on src/components/DataTable.tsx
> +                    {rows.map(row => <tr>{Object.values(row).map(v => <td>{v}</td>)}</tr>)}
Добавить ключи ко всему в map. Учитывая что у тебя никогда не изменяется порядок и ты ничего не удаляешь, это могут быть просто индексы по массиву

2023-09-30 12:22 UTC, tyrkinn commented on src/components/DataTable.tsx
> +    console.log(rows)
Когда ты кидаешь PR не должно оставаться console.log ов

2023-09-30 12:22 UTC, tyrkinn commented on src/components/DataTable.tsx
> +    const rows = Object.values(table)
Переменная rows тебе здесь абсолютно ненужна. Ты можешь использовать table.map вместо rows.map ниже

2023-09-30 12:22 UTC, tyrkinn commented on src/components/DataTable.tsx
> +
Для случая когда в table приходит пустой массив, предлагаю принимать headers отдельно как массив строк.

2023-09-30 18:44 UTC, tyrkinn approved these changes

2023-09-30 18:47 UTC, merged